In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.4.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 2s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 2.9570013e-01, -9.4016105e-02, -2.7940837e-01, -9.0178680e-01,
        -6.1496991e-01, -4.4010586e-01,  1.2834492e-01, -2.7013090e-01,
        -3.1092399e-01, -4.2126700e-04]], dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.16324157, 0.11055519, 0.09184686, 0.04929113, 0.06566467,
        0.07821216, 0.13808589, 0.09270293, 0.08899739, 0.12140229]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.5483303

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 2s 713us/step - loss: 0.4787 - accuracy: 0.8615
Epoch 2/5
1875/1875 [==============================] - 1s 682us/step - loss: 0.1493 - accuracy: 0.9555
Epoch 3/5
1875/1875 [==============================] - 1s 704us/step - loss: 0.1110 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 1s 682us/step - loss: 0.0857 - accuracy: 0.9741
Epoch 5/5
1875/1875 [==============================] - 1s 667us/step - loss: 0.0711 - accuracy: 0.9783


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0695 - accuracy: 0.9779


[0.06947644799947739, 0.9779000282287598]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.4851979e-07, 7.8116660e-09, 1.0578961e-05, 3.0100622e-04,
        2.0334753e-11, 9.4960376e-07, 9.8880442e-13, 9.9968040e-01,
        1.3753038e-06, 5.2526816e-06],
       [1.3169131e-06, 5.1308755e-04, 9.9898595e-01, 4.8654701e-04,
        1.2192824e-13, 9.9296249e-06, 2.5905097e-06, 1.5249310e-12,
        5.6423914e-07, 1.6262122e-12],
       [4.6867328e-07, 9.9944562e-01, 1.3988878e-04, 1.2052963e-05,
        5.2270748e-06, 1.7263253e-06, 1.0170833e-05, 3.3561353e-04,
        4.9048060e-05, 2.8184172e-07],
       [9.9998212e-01, 5.9207622e-10, 1.6949459e-06, 3.5201175e-08,
        4.3584521e-07, 3.2040309e-06, 3.5404260e-06, 6.7466576e-06,
        1.7686494e-08, 2.0967907e-06],
       [8.0881887e-07, 6.8148034e-09, 1.3011089e-06, 4.2061572e-09,
        9.9684650e-01, 1.0632494e-06, 5.2892705e-07, 2.3519551e-05,
        1.4434661e-06, 3.1248615e-03]], dtype=float32)>